# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYaeoECg6vYH8F2MpT9h4y8j-QbZAmXe
"""

"""
Layer Probing for Mistral 7B — Sentiment Analysis
---------------------------------------------------
Goal: Find which layers contain the most linearly decodable sentiment
information, by training a logistic regression probe at each of the 32 layers.

NOTE: High probe accuracy tells us sentiment is *accessible* at that layer.
It does NOT tell us where the sentiment *computation* happens.

Output:
  - Per-layer accuracy, AUC, F1
  - layer_probe_results.png

Dataset: IMDB (richer than SST-2; longer reviews, more compositional sentiment)
Pooling: Mean pooling over non-padding tokens (more stable than last-token)
Hooks:   Registered at transformer layer OUTPUT = residual stream post-MLP
"""

import torch
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score
import matplotlib.pyplot as plt
from tqdm import tqdm

# ── Reproducibility ───────────────────────────────────────────────────────────

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# ── Config ────────────────────────────────────────────────────────────────────

MODEL_NAME  = "mistralai/Mistral-7B-v0.1"
MAX_SAMPLES = 2000             # Training examples; increase for better estimates
MAX_VAL     = 500              # Validation examples
MAX_LENGTH  = 256              # IMDB reviews are longer than SST-2
BATCH_SIZE  = 8                # Reduce to 4 if OOM
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"

# ── Load Model & Tokenizer ────────────────────────────────────────────────────

print("Loading model...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token      = tokenizer.eos_token
tokenizer.padding_side   = "left"   # Left-pad so real tokens are always rightmost

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map="auto"
)
model.eval()

NUM_LAYERS = model.config.num_hidden_layers   # 32
HIDDEN_DIM = model.config.hidden_size         # 4096
print(f"Model loaded: {NUM_LAYERS} layers, hidden dim {HIDDEN_DIM}")

# ── Load Dataset (IMDB) ───────────────────────────────────────────────────────

print("Loading IMDB dataset...")
dataset    = load_dataset("imdb")
train_data = dataset["train"].shuffle(seed=SEED).select(range(MAX_SAMPLES))
val_data   = dataset["test"].shuffle(seed=SEED).select(range(MAX_VAL))
# IMDB columns: "text" (str), "label" (0=neg, 1=pos)

# ── Activation Capture via Hooks ──────────────────────────────────────────────
# Hooks are registered at each transformer layer OUTPUT.
# This captures the RESIDUAL STREAM post-MLP — i.e., the full accumulated
# representation after both attention and MLP have written to it at layer i.
#
# Pooling: masked mean over all non-padding token positions.
# More stable than last-token for sentence-level tasks.

def get_mean_pooled_activations(model, tokenizer, texts, batch_size=BATCH_SIZE):
    """
    Run texts through frozen model, return mean-pooled activations per layer.
    Output shape: [num_texts, num_layers, hidden_dim]
    """
    all_layer_activations  = [[] for _ in range(NUM_LAYERS)]
    current_attention_mask = [None]   # mutable container for hook closure
    hooks = []

    def make_hook(layer_idx):
        def hook(module, input, output):
            # output[0]: [batch, seq_len, hidden_dim]  — residual stream post-MLP
            hidden = output[0].float()                        # cast fp16 -> fp32
            mask   = current_attention_mask[0]                # [batch, seq_len]
            mask_f = mask.unsqueeze(-1).float()               # [batch, seq_len, 1]

            # Mean pool: sum over real tokens, divide by token count
            pooled = (hidden * mask_f).sum(dim=1) / mask_f.sum(dim=1)
            # pooled: [batch, hidden_dim]

            all_layer_activations[layer_idx].append(pooled.detach().cpu())
        return hook

    for i, layer in enumerate(model.model.layers):
        hooks.append(layer.register_forward_hook(make_hook(i)))

    with torch.no_grad():
        for start in tqdm(range(0, len(texts), batch_size), desc="Capturing activations"):
            batch_texts = texts[start : start + batch_size]
            encoded = tokenizer(
                batch_texts,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=MAX_LENGTH
            ).to(DEVICE)
            current_attention_mask[0] = encoded["attention_mask"]
            model(**encoded)

    for h in hooks:
        h.remove()

    layer_tensors = [torch.cat(acts, dim=0) for acts in all_layer_activations]
    return torch.stack(layer_tensors, dim=1).numpy()   # [N, 32, 4096]


# ── Collect Activations ───────────────────────────────────────────────────────

print("\nCapturing train activations...")
train_texts  = train_data["text"]
train_labels = np.array(train_data["label"])
train_acts   = get_mean_pooled_activations(model, tokenizer, train_texts)

print("\nCapturing validation activations...")
val_texts  = val_data["text"]
val_labels = np.array(val_data["label"])
val_acts   = get_mean_pooled_activations(model, tokenizer, val_texts)

# ── Linear Probe (PyTorch) ───────────────────────────────────────────────────
# Replaces sklearn LogisticRegression — faster, runs on GPU, no joblib issues.
# Simple 1-layer linear model trained with Adam for 300 steps per layer.

def train_linear_probe(X_train, y_train, X_val, y_val,
                       lr=1e-3, steps=300, batch_size=256):
    """
    X_train: numpy [N, hidden_dim]
    y_train: numpy [N]
    Returns: acc, auc, f1 on validation set
    """
    input_dim = X_train.shape[1]

    # Normalise on CPU before moving to GPU
    mean = X_train.mean(axis=0)
    std  = X_train.std(axis=0) + 1e-8
    X_train = (X_train - mean) / std
    X_val   = (X_val   - mean) / std

    # Convert to tensors
    Xt = torch.tensor(X_train, dtype=torch.float32).to(DEVICE)
    yt = torch.tensor(y_train, dtype=torch.float32).to(DEVICE)
    Xv = torch.tensor(X_val,   dtype=torch.float32).to(DEVICE)

    # Simple linear layer
    probe = torch.nn.Linear(input_dim, 1).to(DEVICE)
    opt   = torch.optim.Adam(probe.parameters(), lr=lr)
    loss_fn = torch.nn.BCEWithLogitsLoss()

    # Mini-batch training
    n = Xt.size(0)
    for step in range(steps):
        idx    = torch.randperm(n, device=DEVICE)[:batch_size]
        logits = probe(Xt[idx]).squeeze(1)
        loss   = loss_fn(logits, yt[idx])
        opt.zero_grad()
        loss.backward()
        opt.step()

    # Evaluate on validation set
    with torch.no_grad():
        logits_val = probe(Xv).squeeze(1).cpu().numpy()
        probs_val  = torch.sigmoid(torch.tensor(logits_val)).numpy()
        preds_val  = (probs_val >= 0.5).astype(int)

    acc = accuracy_score(y_val, preds_val)
    auc = roc_auc_score(y_val, probs_val)
    f1  = f1_score(y_val, preds_val)
    return acc, auc, f1


# ── Train Probes at Each Layer ────────────────────────────────────────────────

print("\nTraining probes at each layer...")

results = []

for layer_idx in range(NUM_LAYERS):
    X_train = train_acts[:, layer_idx, :]   # [N, 4096]
    X_val   = val_acts[:, layer_idx, :]     # [M, 4096]

    acc, auc, f1 = train_linear_probe(X_train, train_labels, X_val, val_labels)

    results.append({
        "layer" : layer_idx + 1,
        "acc"   : acc,
        "auc"   : auc,
        "f1"    : f1,
    })

    print(f"  Layer {layer_idx+1:2d} | acc={acc:.3f}  auc={auc:.3f}  f1={f1:.3f}")

# ── Plot Results ──────────────────────────────────────────────────────────────

print("\nPlotting...")
layers = [r["layer"] for r in results]
accs   = [r["acc"]   for r in results]
aucs   = [r["auc"]   for r in results]

fig, axes = plt.subplots(2, 1, figsize=(14, 9), sharex=True)

# ── Top plot: Accuracy ──
axes[0].plot(layers, accs, marker='o', linewidth=2, markersize=5,
             color='steelblue', label='Accuracy')
axes[0].axhline(y=0.5, color='gray', linestyle=':', alpha=0.5, label='Random baseline (0.5)')
axes[0].set_ylabel("Accuracy")
axes[0].set_title(
    "Mistral 7B — Linearly Decodable Sentiment per Layer (IMDB)\n"
    "NOTE: measures information accessibility, not where computation occurs"
)
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# ── Bottom plot: AUC ──
axes[1].plot(layers, aucs, marker='s', linewidth=2, markersize=5,
             color='mediumseagreen', label='AUC-ROC')
axes[1].axhline(y=0.5, color='gray', linestyle=':', alpha=0.5, label='Random baseline (0.5)')
axes[1].set_xlabel("Layer")
axes[1].set_ylabel("AUC-ROC")
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.xticks(layers)
plt.tight_layout()
plt.savefig("layer_probe_results.png", dpi=150)
plt.show()

# ── Summary ───────────────────────────────────────────────────────────────────

print("\n── Layer Ranking by AUC ──")
ranked = sorted(results, key=lambda r: r["auc"], reverse=True)
for r in ranked[:10]:
    print(f"  Layer {r['layer']:2d} | acc={r['acc']:.3f}  auc={r['auc']:.3f}  f1={r['f1']:.3f}")

print("\nInspect the plot and table above to select target layers for SAE training.")
print("Prioritise layers with high AUC — these carry the clearest sentiment signal.")

"""
Step 2 — SAE Training for Mistral 7B (All 32 Layers)
------------------------------------------------------
Trains a Sparse Autoencoder on residual stream activations
for every layer in Mistral 7B.

Key design decisions:
  - All 32 layers trained (not just sentiment layers)
    → gives SAE-based importance scores everywhere
    → prune.py can use principled pruning across whole model
  - Early stopping based on reconstruction loss plateau
    → avoids over-training on small datasets
    → typically converges in 5k-10k steps for 2000 examples
  - Activations saved to disk on first run, reused on subsequent runs
    → never re-run Mistral just to retrain an SAE

SAE Architecture:
  Input [4096]
    → subtract b_dec           (centering trick)
    → Linear(4096→32768) + ReLU (encoder)
    → sparse features [32768]
    → Linear(32768→4096)        (decoder, no bias)
    → add b_dec back
  Output reconstruction [4096]

Loss = MSE(input, reconstruction) + L1_COEFF × L1(features)

File structure produced:
  activations/
    layer_{N}_train.npy    shape [N_TRAIN, 4096]
    layer_{N}_val.npy      shape [N_VAL,   4096]
  sae_models/
    sae_layer_{N}.pt       trained SAE weights + config

Estimated training time (all 32 layers, early stopping):
  A100:      ~20 minutes
  T4/Colab:  ~80 minutes
"""

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm

# ── Reproducibility ───────────────────────────────────────────────────────────

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# ── Config ────────────────────────────────────────────────────────────────────

MODEL_NAME  = "mistralai/Mistral-7B-v0.1"
HIDDEN_DIM  = 4096
DICT_SIZE   = HIDDEN_DIM * 4     # 16384 — 4x expansion (2x faster than 8x)
L1_COEFF    = 8e-4               # stronger sparsity → faster convergence
LR          = 2e-4
BATCH_SIZE  = 512

# Early stopping — stops when reconstruction loss stops improving
MIN_STEPS     = 5_000    # always run at least this many steps
MAX_STEPS     = 50_000   # hard upper limit
LOG_EVERY     = 500      # evaluate and log every N steps
PATIENCE      = 5        # stop after this many LOG_EVERY checks with no improvement
MIN_DELTA     = 1e-4     # minimum improvement to count as progress

# Dataset
N_TRAIN     = 2000
N_VAL       = 500
MAX_LENGTH  = 256
ACT_BATCH   = 8          # batch size for activation capture (Mistral forward pass)

# All 32 layers
TARGET_LAYERS = list(range(32))

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ── Google Drive paths — survives Colab session restarts ──────────────────────
# Mount Drive first: from google.colab import drive; drive.mount('/content/drive')
DRIVE_ROOT = "/content/drive/MyDrive/sae_pruning"
ACT_DIR    = f"{DRIVE_ROOT}/activations"
SAE_DIR    = f"{DRIVE_ROOT}/sae_models"
os.makedirs(ACT_DIR, exist_ok=True)
os.makedirs(SAE_DIR, exist_ok=True)

# ── SAE Architecture ──────────────────────────────────────────────────────────

class SparseAutoencoder(nn.Module):
    """
    Sparse Autoencoder for one layer's residual stream.

    b_dec (pre-encoder bias):
      Subtracted before encoding, added after decoding.
      Lets encoder focus on directions not offsets.

    Decoder columns kept unit-norm:
      Prevents large decoder weights from trivially absorbing
      the L1 sparsity penalty.
    """

    def __init__(self, input_dim: int, dict_size: int):
        super().__init__()
        self.input_dim = input_dim
        self.dict_size = dict_size

        self.b_dec = nn.Parameter(torch.zeros(input_dim))
        self.W_enc = nn.Parameter(
            torch.nn.init.kaiming_uniform_(torch.empty(input_dim, dict_size))
        )
        self.b_enc = nn.Parameter(torch.zeros(dict_size))
        self.W_dec = nn.Parameter(
            torch.nn.init.kaiming_uniform_(torch.empty(dict_size, input_dim))
        )
        self._normalize_decoder()

    @torch.no_grad()
    def _normalize_decoder(self):
        self.W_dec.data = F.normalize(self.W_dec.data, dim=1)

    def forward(self, x):
        x_centered     = x - self.b_dec
        features       = F.relu(x_centered @ self.W_enc + self.b_enc)
        reconstruction = features @ self.W_dec + self.b_dec
        return features, reconstruction

    def encode_only(self, x):
        return F.relu((x - self.b_dec) @ self.W_enc + self.b_enc)

    def compute_loss(self, x, features, reconstruction):
        recon_loss    = (x - reconstruction).pow(2).sum(dim=-1).mean()
        sparsity_loss = features.abs().sum(dim=-1).mean()
        total         = recon_loss + L1_COEFF * sparsity_loss
        return total, recon_loss, sparsity_loss


# ── Activation Capture ────────────────────────────────────────────────────────

def capture_and_save_activations(model, tokenizer):
    """
    Run Mistral on train + val data, capture mean-pooled residual stream
    activations at ALL 32 layers in one forward pass.
    Saves each layer's activations as a separate .npy file.

    Hooks fire at transformer layer OUTPUT = post-MLP residual stream.
    Mean pooling over non-padding tokens — more stable than last-token.
    """
    print("Loading IMDB dataset...")
    dataset    = load_dataset("imdb")
    train_data = dataset["train"].shuffle(seed=SEED).select(range(N_TRAIN))
    val_data   = dataset["test"].shuffle(seed=SEED).select(range(N_VAL))

    def capture_split(texts, split_name):
        # One list per layer to accumulate batch results
        layer_acts   = {l: [] for l in TARGET_LAYERS}
        current_mask = [None]
        hooks        = []

        def make_hook(layer_idx):
            def hook(module, input, output):
                hidden = output[0].float()                        # [b, seq, 4096]
                mask   = current_mask[0].unsqueeze(-1).float()    # [b, seq, 1]
                pooled = (hidden * mask).sum(dim=1) / mask.sum(dim=1)  # [b, 4096]
                layer_acts[layer_idx].append(pooled.detach().cpu())
            return hook

        for layer_idx in TARGET_LAYERS:
            h = model.model.layers[layer_idx].register_forward_hook(make_hook(layer_idx))
            hooks.append(h)

        with torch.no_grad():
            for start in tqdm(range(0, len(texts), ACT_BATCH),
                              desc=f"  Capturing {split_name}"):
                batch   = texts[start : start + ACT_BATCH]
                encoded = tokenizer(
                    batch,
                    return_tensors="pt",
                    padding=True,
                    truncation=True,
                    max_length=MAX_LENGTH
                ).to(DEVICE)
                current_mask[0] = encoded["attention_mask"]
                model(**encoded)

        for h in hooks:
            h.remove()

        for layer_idx in TARGET_LAYERS:
            arr  = torch.cat(layer_acts[layer_idx], dim=0).numpy()
            path = os.path.join(ACT_DIR, f"layer_{layer_idx}_{split_name}.npy")
            np.save(path, arr)

        print(f"  Saved {len(TARGET_LAYERS)} layers × {len(texts)} examples → {ACT_DIR}/")

    capture_split(train_data["text"], "train")
    capture_split(val_data["text"],   "val")


def activations_exist():
    """Check all 32 layers × both splits are on disk."""
    for layer_idx in TARGET_LAYERS:
        for split in ["train", "val"]:
            if not os.path.exists(os.path.join(ACT_DIR, f"layer_{layer_idx}_{split}.npy")):
                return False
    return True


def load_activations(layer_idx):
    train = torch.tensor(
        np.load(os.path.join(ACT_DIR, f"layer_{layer_idx}_train.npy")),
        dtype=torch.float32
    )
    val = torch.tensor(
        np.load(os.path.join(ACT_DIR, f"layer_{layer_idx}_val.npy")),
        dtype=torch.float32
    )
    return train, val


# ── Training ──────────────────────────────────────────────────────────────────

def train_sae(layer_idx: int, train_acts: torch.Tensor) -> tuple:
    """
    Train one SAE with early stopping.
    Returns (trained_sae, steps_run, final_recon_loss).
    """
    sae       = SparseAutoencoder(HIDDEN_DIM, DICT_SIZE).to(DEVICE)
    optimizer = torch.optim.Adam(sae.parameters(), lr=LR)
    dataset   = TensorDataset(train_acts)
    loader    = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)
    data_iter = iter(loader)

    # Dead feature tracking
    steps_since_active = torch.zeros(DICT_SIZE, dtype=torch.long)

    # Early stopping state
    best_recon_loss = float('inf')
    patience_count  = 0
    steps_run       = 0

    for step in range(1, MAX_STEPS + 1):
        steps_run = step

        # Cycle data
        try:
            (x,) = next(data_iter)
        except StopIteration:
            data_iter = iter(loader)
            (x,) = next(data_iter)

        x = x.to(DEVICE)
        features, reconstruction = sae(x)
        total, recon_loss, sparsity_loss = sae.compute_loss(x, features, reconstruction)

        optimizer.zero_grad()
        total.backward()
        optimizer.step()
        sae._normalize_decoder()

        # Dead feature tracking
        with torch.no_grad():
            fired = (features > 0).any(dim=0).cpu()
            steps_since_active[fired]  = 0
            steps_since_active[~fired] += 1

        # ── Early stopping check ──
        if step % LOG_EVERY == 0:
            with torch.no_grad():
                mean_active = (features > 0).float().sum(dim=1).mean().item()
                dead_pct    = 100 * (steps_since_active > 10_000).sum().item() / DICT_SIZE
                recon_val   = recon_loss.item()

            print(f"    Step {step:>6} | "
                  f"recon={recon_val:.4f}  "
                  f"l1={sparsity_loss.item():.4f}  "
                  f"active={mean_active:.1f}  "
                  f"dead={dead_pct:.1f}%")

            if step >= MIN_STEPS:
                if recon_val < best_recon_loss - MIN_DELTA:
                    best_recon_loss = recon_val
                    patience_count  = 0
                else:
                    patience_count += 1

                if patience_count >= PATIENCE:
                    print(f"    Early stopping at step {step} "
                          f"(no improvement for {PATIENCE} checks)")
                    break

    return sae, steps_run, best_recon_loss


# ── Evaluation ────────────────────────────────────────────────────────────────

@torch.no_grad()
def evaluate_sae(sae, val_acts, layer_idx):
    """
    Health check metrics on validation activations.
    These verify SAE quality — not sentiment accuracy.

    Metrics:
      Explained variance: 1 - var(residual)/var(input)  → higher is better
      Mean active features: avg features firing per token → lower is sparser
      Dead features %: never fired on val set            → lower is better
    """
    sae.eval()
    val_acts = val_acts.to(DEVICE)
    features, reconstruction = sae(val_acts)

    var_in   = val_acts.var(dim=0).sum().item()
    var_res  = (val_acts - reconstruction).var(dim=0).sum().item()
    expl_var = 1 - var_res / (var_in + 1e-8)

    mean_active = (features > 0).float().sum(dim=1).mean().item()
    dead_pct    = 100 * (features.max(dim=0).values == 0).float().mean().item()

    status = "✓" if expl_var > 0.80 else "⚠"
    print(f"  {status} expl_var={expl_var:.3f}  "
          f"active/token={mean_active:.1f}  "
          f"dead={dead_pct:.1f}%")

    if expl_var < 0.80:
        print(f"    → Low explained variance. Try reducing L1_COEFF ({L1_COEFF}) "
              f"or increasing DICT_SIZE ({DICT_SIZE})")
    if dead_pct > 30:
        print(f"    → Many dead features. Try reducing L1_COEFF or increasing LR")

    sae.train()
    return expl_var, mean_active, dead_pct


# ── Save / Load ───────────────────────────────────────────────────────────────

def save_sae(sae, layer_idx, steps_run, expl_var):
    path = os.path.join(SAE_DIR, f"sae_layer_{layer_idx}.pt")
    torch.save({
        "state_dict" : sae.state_dict(),
        "input_dim"  : sae.input_dim,
        "dict_size"  : sae.dict_size,
        "layer_idx"  : layer_idx,
        "l1_coeff"   : L1_COEFF,
        "steps_run"  : steps_run,
        "expl_var"   : expl_var,
    }, path)


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # ── Check Google Drive is mounted ──
    if not os.path.exists("/content/drive/MyDrive"):
        print("ERROR: Google Drive not mounted.")
        print("Run this first:")
        print("  from google.colab import drive")
        print("  drive.mount('/content/drive')")
        exit(1)
    print(f"Google Drive mounted ✓  Saving to: {DRIVE_ROOT}")

    # ── Step A: Capture activations (once, reused across all SAE runs) ──
    if activations_exist():
        print("Activations already on disk — skipping capture.")
        print(f"  ({len(TARGET_LAYERS)} layers × 2 splits found in {ACT_DIR}/)")
    else:
        missing = [
            l for l in TARGET_LAYERS
            if not os.path.exists(os.path.join(ACT_DIR, f"layer_{l}_train.npy"))
        ]
        print(f"Missing activations for {len(missing)} layers — loading Mistral...")
        tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
        tokenizer.pad_token    = tokenizer.eos_token
        tokenizer.padding_side = "left"

        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.float16,
            device_map="auto"
        )
        model.eval()
        capture_and_save_activations(model, tokenizer)

        del model
        torch.cuda.empty_cache()
        print("Model unloaded — GPU memory freed for SAE training.\n")

    # ── Step B: Train one SAE per layer ──
    results = []

    for layer_idx in TARGET_LAYERS:
        sae_path = os.path.join(SAE_DIR, f"sae_layer_{layer_idx}.pt")

        if os.path.exists(sae_path):
            print(f"Layer {layer_idx:2d}: SAE already trained — skipping. "
                  f"(Delete {sae_path} to retrain)")
            continue

        print(f"\n── Layer {layer_idx:2d} / {max(TARGET_LAYERS)} ──")
        train_acts, val_acts = load_activations(layer_idx)
        print(f"  Train: {train_acts.shape}  Val: {val_acts.shape}")

        sae, steps_run, final_loss = train_sae(layer_idx, train_acts)

        print(f"  Evaluating...")
        expl_var, mean_active, dead_pct = evaluate_sae(sae, val_acts, layer_idx)

        save_sae(sae, layer_idx, steps_run, expl_var)
        print(f"  Saved → {sae_path}  (steps={steps_run})")

        results.append({
            "layer"      : layer_idx,
            "steps"      : steps_run,
            "expl_var"   : expl_var,
            "mean_active": mean_active,
            "dead_pct"   : dead_pct,
        })

    # ── Summary ──
    if results:
        print(f"\n{'─'*60}")
        print(f"{'Layer':>6} {'Steps':>8} {'ExplVar':>8} {'Active':>8} {'Dead%':>7}")
        print(f"{'─'*60}")
        for r in results:
            flag = " ⚠" if r["expl_var"] < 0.80 or r["dead_pct"] > 30 else ""
            print(f"  {r['layer']:>4}  {r['steps']:>8}  {r['expl_var']:>7.3f}  "
                  f"{r['mean_active']:>7.1f}  {r['dead_pct']:>6.1f}%{flag}")

    print(f"\n── Step 2 Complete ──")
    print(f"All 32 SAEs trained and saved to {SAE_DIR}/")
    print(f"Next: Step 3 — find sentiment-correlated features in all 32 SAEs.")

from google.colab import drive
drive.mount('/content/drive')

import shutil, os

# Create folder on Drive
save_path = '/content/drive/MyDrive/sae_pruning'
os.makedirs(f'{save_path}/activations', exist_ok=True)
os.makedirs(f'{save_path}/sae_models',  exist_ok=True)

# Copy activations
if os.path.exists('/content/activations'):
    shutil.copytree('/content/activations', f'{save_path}/activations', dirs_exist_ok=True)
    print("Activations copied ✓")
else:
    print("No activations folder found")

# Copy SAE models
if os.path.exists('/content/sae_models'):
    shutil.copytree('/content/sae_models', f'{save_path}/sae_models', dirs_exist_ok=True)
    print("SAE models copied ✓")
else:
    print("No sae_models folder found")

print(f"\nAll saved to: {save_path}")

# ── Run this FIRST every new Colab session ────────────────────────────────────

from google.colab import drive
drive.mount('/content/drive')

import shutil, os

DRIVE_PATH = '/content/drive/MyDrive/sae_pruning'

# Restore activations
if os.path.exists(f'{DRIVE_PATH}/activations'):
    shutil.copytree(f'{DRIVE_PATH}/activations', '/content/activations', dirs_exist_ok=True)
    n = len(os.listdir('/content/activations'))
    print(f"Activations restored ✓  ({n} files)")
else:
    print("No activations on Drive — will be captured fresh")

# Restore SAE models
if os.path.exists(f'{DRIVE_PATH}/sae_models'):
    shutil.copytree(f'{DRIVE_PATH}/sae_models', '/content/sae_models', dirs_exist_ok=True)
    n = len(os.listdir('/content/sae_models'))
    print(f"SAE models restored ✓  ({n} files)")
else:
    print("No SAE models on Drive yet")

print("\nReady — run sae_train.py to continue from where you left off.")

"""
Step 3 — Find Sentiment-Correlated SAE Features (All 32 Layers)
----------------------------------------------------------------
Runs saved activations through trained SAEs to get feature activations,
then scores each feature by how well it separates positive vs negative sentiment.

This is CORRELATION only — causality is verified in Step 4.

Inputs (from previous steps):
  {DRIVE_ROOT}/activations/layer_{N}_train.npy   shape [2000, 4096]
  {DRIVE_ROOT}/activations/layer_{N}_val.npy     shape [500,  4096]
  {DRIVE_ROOT}/sae_models/sae_layer_{N}.pt       trained SAE

Output:
  {DRIVE_ROOT}/feature_scores/layer_{N}_scores.npy   shape [dict_size, 3]
                                                        col0: sentiment_score (signed)
                                                        col1: abs_score (for ranking)
                                                        col2: activation_frequency
  {DRIVE_ROOT}/feature_scores/layer_{N}_topk.npy     top-K feature indices

Scoring:
  sentiment_score = mean(feature | positive) - mean(feature | negative)
    > 0  → fires more on positive examples
    < 0  → fires more on negative examples
    ~ 0  → not sentiment relevant

  activation_frequency = fraction of examples where feature fires (> 0)
    Features firing on < MIN_FREQ examples are unreliable.
"""

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

# ── Reproducibility ───────────────────────────────────────────────────────────

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# ── Config ────────────────────────────────────────────────────────────────────

TARGET_LAYERS = list(range(32))
TOP_K         = 200      # top features to keep per layer for Step 4
MIN_FREQ      = 0.01     # feature must fire on ≥1% of examples to count
ENCODE_BATCH  = 256      # batch size for SAE encoding (no Mistral needed)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ── Google Drive paths ────────────────────────────────────────────────────────
DRIVE_ROOT  = "/content/drive/MyDrive/sae_pruning"
ACT_DIR     = f"{DRIVE_ROOT}/activations"
SAE_DIR     = f"{DRIVE_ROOT}/sae_models"
SCORE_DIR   = f"{DRIVE_ROOT}/feature_scores"
os.makedirs(SCORE_DIR, exist_ok=True)

# ── SAE (must match sae_train.py) ─────────────────────────────────────────────

class SparseAutoencoder(nn.Module):
    def __init__(self, input_dim, dict_size):
        super().__init__()
        self.input_dim = input_dim
        self.dict_size = dict_size
        self.b_dec = nn.Parameter(torch.zeros(input_dim))
        self.W_enc = nn.Parameter(torch.empty(input_dim, dict_size))
        self.b_enc = nn.Parameter(torch.zeros(dict_size))
        self.W_dec = nn.Parameter(torch.empty(dict_size, input_dim))

    def encode_only(self, x):
        return F.relu((x - self.b_dec) @ self.W_enc + self.b_enc)


def load_sae(layer_idx):
    path       = os.path.join(SAE_DIR, f"sae_layer_{layer_idx}.pt")
    checkpoint = torch.load(path, map_location=DEVICE)
    sae        = SparseAutoencoder(checkpoint["input_dim"], checkpoint["dict_size"])
    sae.load_state_dict(checkpoint["state_dict"])
    sae.to(DEVICE).eval()
    return sae, checkpoint["dict_size"]


def load_activations(layer_idx):
    train = torch.tensor(
        np.load(os.path.join(ACT_DIR, f"layer_{layer_idx}_train.npy")),
        dtype=torch.float32
    )
    val = torch.tensor(
        np.load(os.path.join(ACT_DIR, f"layer_{layer_idx}_val.npy")),
        dtype=torch.float32
    )
    return train, val


# ── Get Feature Activations ───────────────────────────────────────────────────

@torch.no_grad()
def get_feature_activations(sae, activations, batch_size=ENCODE_BATCH):
    """
    Run activations through SAE encoder in batches.
    activations: [N, hidden_dim]
    returns:     [N, dict_size] sparse feature activations
    No Mistral needed — just SAE encoder.
    """
    all_features = []
    for start in range(0, activations.size(0), batch_size):
        batch    = activations[start : start + batch_size].to(DEVICE)
        features = sae.encode_only(batch).cpu()
        all_features.append(features)
    return torch.cat(all_features, dim=0)


# ── Score Features ────────────────────────────────────────────────────────────

def score_features(feature_acts, labels):
    """
    feature_acts: [N, dict_size] tensor
    labels:       [N] numpy array (0=neg, 1=pos)

    Returns [dict_size, 3]:
      col 0: sentiment_score  = mean(pos) - mean(neg)   signed
      col 1: abs_score        = |sentiment_score|        for ranking
      col 2: activation_freq  = fraction of examples where feature > 0
    """
    labels_t  = torch.tensor(labels, dtype=torch.bool)
    pos_acts  = feature_acts[labels_t]    # [n_pos, dict_size]
    neg_acts  = feature_acts[~labels_t]   # [n_neg, dict_size]

    mean_pos        = pos_acts.mean(dim=0).numpy()
    mean_neg        = neg_acts.mean(dim=0).numpy()
    sentiment_score = mean_pos - mean_neg
    abs_score       = np.abs(sentiment_score)
    act_freq        = (feature_acts > 0).float().mean(dim=0).numpy()

    return np.stack([sentiment_score, abs_score, act_freq], axis=1)


def select_top_features(scores, top_k, min_freq):
    """
    Rank features by abs_score, filter out rarely-firing ones.
    Returns indices of top_k features.
    """
    masked = scores[:, 1].copy()
    masked[scores[:, 2] < min_freq] = 0.0   # zero out rare features
    return np.argsort(masked)[::-1][:top_k].astype(np.int32)


# ── Plot ──────────────────────────────────────────────────────────────────────

def plot_and_save(scores, top_indices, layer_idx):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Score distribution
    axes[0].hist(scores[:, 1], bins=100, color='steelblue', alpha=0.7)
    axes[0].axvline(x=scores[top_indices[-1], 1], color='red',
                    linestyle='--', label=f'Top-{TOP_K} cutoff')
    axes[0].set_xlabel("Absolute Sentiment Score")
    axes[0].set_ylabel("Number of Features")
    axes[0].set_title(f"Layer {layer_idx} — Score Distribution\n"
                      f"Most features near zero = not sentiment relevant")
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Top features signed scores
    top_scores = scores[top_indices, 0]
    colors     = ['steelblue' if s > 0 else 'tomato' for s in top_scores]
    axes[1].bar(range(len(top_indices)), top_scores, color=colors, alpha=0.8)
    axes[1].axhline(y=0, color='black', linewidth=0.8)
    axes[1].set_xlabel("Feature Rank")
    axes[1].set_ylabel("Sentiment Score")
    axes[1].set_title(f"Layer {layer_idx} — Top {TOP_K} Features\n"
                      f"Blue = positive-biased   Red = negative-biased")
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    path = os.path.join(SCORE_DIR, f"layer_{layer_idx}_scores.png")
    plt.savefig(path, dpi=150)
    plt.close()


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # Check Drive mounted
    if not os.path.exists(DRIVE_ROOT):
        print("ERROR: Google Drive not mounted or sae_pruning folder missing.")
        print("Run: from google.colab import drive; drive.mount('/content/drive')")
        exit(1)

    # Load labels — same split as sae_train.py
    from datasets import load_dataset
    dataset      = load_dataset("imdb")
    train_data   = dataset["train"].shuffle(seed=SEED).select(range(2000))
    train_labels = np.array(train_data["label"])

    # Check which layers have trained SAEs
    available = [
        l for l in TARGET_LAYERS
        if os.path.exists(os.path.join(SAE_DIR, f"sae_layer_{l}.pt"))
    ]
    print(f"SAEs available: {len(available)} / 32 layers")
    print(f"Processing:     {available}\n")

    summary = []

    for layer_idx in available:

        # Skip if already scored
        score_path = os.path.join(SCORE_DIR, f"layer_{layer_idx}_scores.npy")
        topk_path  = os.path.join(SCORE_DIR, f"layer_{layer_idx}_topk.npy")
        if os.path.exists(score_path) and os.path.exists(topk_path):
            print(f"Layer {layer_idx:2d}: already scored — skipping")
            continue

        print(f"── Layer {layer_idx:2d} ──")

        # Load SAE and activations
        sae, dict_size   = load_sae(layer_idx)
        train_acts, _    = load_activations(layer_idx)

        # Encode activations → sparse features
        print(f"  Encoding {len(train_acts)} examples through SAE...")
        train_features = get_feature_activations(sae, train_acts)
        # train_features: [2000, dict_size]

        # Score all features
        scores      = score_features(train_features, train_labels)
        top_indices = select_top_features(scores, TOP_K, MIN_FREQ)

        # Summary stats
        n_pos = (scores[top_indices, 0] > 0).sum()
        n_neg = (scores[top_indices, 0] < 0).sum()
        top5  = top_indices[:5]
        print(f"  Top-{TOP_K}: {n_pos} positive-biased  {n_neg} negative-biased")
        print(f"  Top 5 features:")
        for rank, idx in enumerate(top5):
            direction = "pos" if scores[idx, 0] > 0 else "neg"
            print(f"    #{rank+1}: feature {idx:>5}  "
                  f"score={scores[idx, 0]:+.4f}  "
                  f"freq={scores[idx, 2]:.3f}  "
                  f"bias={direction}")

        # Save to Drive
        np.save(score_path, scores)
        np.save(topk_path,  top_indices)
        plot_and_save(scores, top_indices, layer_idx)
        print(f"  Saved → {SCORE_DIR}/\n")

        summary.append((layer_idx, n_pos, n_neg,
                        float(scores[top_indices[0], 1])))

        # Free memory
        del sae, train_acts, train_features
        torch.cuda.empty_cache()

    # ── Summary ──
    print(f"\n── Step 3 Complete ──")
    print(f"{'Layer':>6}  {'Pos-biased':>11}  {'Neg-biased':>11}  {'Top score':>10}")
    print(f"{'─'*45}")
    for layer_idx, n_pos, n_neg, top_score in summary:
        print(f"  {layer_idx:>4}  {n_pos:>11}  {n_neg:>11}  {top_score:>10.4f}")

    print(f"\nTop-{TOP_K} candidate features saved per layer → {SCORE_DIR}/")
    print("Next: Step 4 — verify which features causally drive sentiment.")

"""
Step 4 — Causal Feature Verification (All 32 Layers)
------------------------------------------------------
Tests which of the top-K candidate features from Step 3 actually
CAUSE sentiment predictions, not just correlate with them.

Method: ablation patching — zero out one feature at a time,
reconstruct the modified activation, run the linear probe,
measure how many predictions flip.

No Mistral needed — works entirely from saved activations on disk.

Efficiency trick:
  full_recon    = features @ W_dec + b_dec          (once per layer)
  ablated_recon = full_recon - feat[:,f] * W_dec[f] (per feature, cheap)

Inputs:
  {DRIVE_ROOT}/activations/layer_{N}_train.npy
  {DRIVE_ROOT}/sae_models/sae_layer_{N}.pt
  {DRIVE_ROOT}/feature_scores/layer_{N}_topk.npy

Output:
  {DRIVE_ROOT}/causal_features/layer_{N}_causal.npy        causal feature indices
  {DRIVE_ROOT}/causal_features/layer_{N}_causal_stats.npy  flip_rate + score_delta
"""

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

# ── Reproducibility ───────────────────────────────────────────────────────────

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# ── Config ────────────────────────────────────────────────────────────────────

TARGET_LAYERS  = list(range(32))
FLIP_THRESHOLD = 0.05    # feature must flip ≥5% of predictions to be causal
PROBE_STEPS    = 300
PROBE_LR       = 1e-3
PROBE_BATCH    = 256
N_TRAIN        = 2000

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ── Google Drive paths ────────────────────────────────────────────────────────

DRIVE_ROOT  = "/content/drive/MyDrive/sae_pruning"
ACT_DIR     = f"{DRIVE_ROOT}/activations"
SAE_DIR     = f"{DRIVE_ROOT}/sae_models"
SCORE_DIR   = f"{DRIVE_ROOT}/feature_scores"
CAUSAL_DIR  = f"{DRIVE_ROOT}/causal_features"
os.makedirs(CAUSAL_DIR, exist_ok=True)

# ── SAE ───────────────────────────────────────────────────────────────────────

class SparseAutoencoder(nn.Module):
    def __init__(self, input_dim, dict_size):
        super().__init__()
        self.input_dim = input_dim
        self.dict_size = dict_size
        self.b_dec = nn.Parameter(torch.zeros(input_dim))
        self.W_enc = nn.Parameter(torch.empty(input_dim, dict_size))
        self.b_enc = nn.Parameter(torch.zeros(dict_size))
        self.W_dec = nn.Parameter(torch.empty(dict_size, input_dim))

    def encode_only(self, x):
        return F.relu((x - self.b_dec) @ self.W_enc + self.b_enc)

    def decode_only(self, features):
        return features @ self.W_dec + self.b_dec


def load_sae(layer_idx):
    path       = os.path.join(SAE_DIR, f"sae_layer_{layer_idx}.pt")
    checkpoint = torch.load(path, map_location=DEVICE)
    sae        = SparseAutoencoder(checkpoint["input_dim"], checkpoint["dict_size"])
    sae.load_state_dict(checkpoint["state_dict"])
    sae.to(DEVICE).eval()
    return sae


def load_activations(layer_idx):
    return torch.tensor(
        np.load(os.path.join(ACT_DIR, f"layer_{layer_idx}_train.npy")),
        dtype=torch.float32
    )


# ── Linear Probe ──────────────────────────────────────────────────────────────

class LinearProbe(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, 1)

    def forward(self, x):
        return self.linear(x).squeeze(1)


def train_probe(acts, labels, steps=PROBE_STEPS, lr=PROBE_LR, batch=PROBE_BATCH):
    """Train probe on reconstructed activations (not raw)."""
    mean = acts.mean(axis=0)
    std  = acts.std(axis=0) + 1e-8
    Xt   = torch.tensor((acts - mean) / std, dtype=torch.float32).to(DEVICE)
    yt   = torch.tensor(labels, dtype=torch.float32).to(DEVICE)

    probe   = LinearProbe(acts.shape[1]).to(DEVICE)
    opt     = torch.optim.Adam(probe.parameters(), lr=lr)
    loss_fn = nn.BCEWithLogitsLoss()
    n       = Xt.size(0)

    for _ in range(steps):
        idx  = torch.randperm(n, device=DEVICE)[:batch]
        loss = loss_fn(probe(Xt[idx]), yt[idx])
        opt.zero_grad(); loss.backward(); opt.step()

    # Store normalisation stats for use during ablation
    probe.mean = torch.tensor(mean, dtype=torch.float32).to(DEVICE)
    probe.std  = torch.tensor(std,  dtype=torch.float32).to(DEVICE)
    probe.eval()
    return probe


@torch.no_grad()
def probe_predict(probe, acts_tensor):
    """acts_tensor: raw (un-normalised) [N, hidden_dim] on DEVICE."""
    normed = (acts_tensor - probe.mean) / probe.std
    probs  = torch.sigmoid(probe(normed)).cpu().numpy()
    preds  = (probs >= 0.5).astype(int)
    return probs, preds


# ── Ablation ──────────────────────────────────────────────────────────────────

@torch.no_grad()
def compute_ablation_stats(sae, probe, acts, candidate_indices, batch_size=512):
    """
    For each candidate feature f:
      ablated = full_recon - feat_act[:,f] * W_dec[f]
    Measure flip_rate and score_delta vs baseline.

    Returns stats: [K, 2]  col0=flip_rate  col1=score_delta
    """
    W_dec = sae.W_dec.data    # [dict_size, hidden_dim]
    b_dec = sae.b_dec.data    # [hidden_dim]
    n     = acts.size(0)

    # ── Step 1: encode all examples, compute full reconstruction ──
    all_features = []
    all_recons   = []

    for start in range(0, n, batch_size):
        batch    = acts[start : start + batch_size].to(DEVICE)
        features = sae.encode_only(batch)
        recon    = features @ W_dec + b_dec
        all_features.append(features.cpu())
        all_recons.append(recon.cpu())

    features_all = torch.cat(all_features, dim=0)   # [N, dict_size]
    recons_all   = torch.cat(all_recons,   dim=0)   # [N, hidden_dim]

    # ── Step 2: baseline predictions ──
    baseline_probs, baseline_preds = probe_predict(probe, recons_all.to(DEVICE))

    # ── Step 3: ablate each candidate feature ──
    stats = np.zeros((len(candidate_indices), 2), dtype=np.float32)

    for i, feat_idx in enumerate(tqdm(candidate_indices, desc="  Ablating", leave=False)):
        feat_act     = features_all[:, feat_idx].unsqueeze(1)      # [N, 1]
        feat_dir     = W_dec[feat_idx].unsqueeze(0).cpu()          # [1, hidden_dim]
        contribution = feat_act * feat_dir                         # [N, hidden_dim]
        ablated_recon = recons_all - contribution                  # [N, hidden_dim]

        ablated_probs, ablated_preds = probe_predict(
            probe, ablated_recon.to(DEVICE)
        )

        stats[i, 0] = (ablated_preds != baseline_preds).mean()          # flip_rate
        stats[i, 1] = np.abs(ablated_probs - baseline_probs).mean()     # score_delta

    return stats


# ── Plot ──────────────────────────────────────────────────────────────────────

def plot_causal(stats, candidate_indices, causal_mask, layer_idx):
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.scatter(stats[~causal_mask, 0], stats[~causal_mask, 1],
               color='lightgray', alpha=0.6, label='Correlational only', s=30)
    ax.scatter(stats[causal_mask, 0],  stats[causal_mask, 1],
               color='steelblue', alpha=0.9, label='Causal', s=50)
    ax.axvline(x=FLIP_THRESHOLD, color='red', linestyle='--',
               label=f'Flip threshold ({FLIP_THRESHOLD:.0%})')
    ax.set_xlabel("Flip Rate")
    ax.set_ylabel("Mean Score Delta")
    ax.set_title(f"Layer {layer_idx} — Causal vs Correlational\n"
                 f"{causal_mask.sum()} causal / {len(candidate_indices)} candidates")
    ax.legend(); ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(os.path.join(CAUSAL_DIR, f"layer_{layer_idx}_causal.png"), dpi=150)
    plt.close()


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # Check Drive
    if not os.path.exists(DRIVE_ROOT):
        print("ERROR: Google Drive not mounted.")
        print("Run: from google.colab import drive; drive.mount('/content/drive')")
        exit(1)

    # Load labels
    from datasets import load_dataset
    dataset      = load_dataset("imdb")
    train_data   = dataset["train"].shuffle(seed=SEED).select(range(N_TRAIN))
    train_labels = np.array(train_data["label"])

    # Only process layers that have both SAE and feature scores
    available = [
        l for l in TARGET_LAYERS
        if os.path.exists(os.path.join(SAE_DIR,   f"sae_layer_{l}.pt")) and
           os.path.exists(os.path.join(SCORE_DIR, f"layer_{l}_topk.npy"))
    ]
    print(f"Layers ready for causal verification: {len(available)}")
    print(f"Layers: {available}\n")

    summary = []

    for layer_idx in available:

        # Skip if already done
        causal_path = os.path.join(CAUSAL_DIR, f"layer_{layer_idx}_causal.npy")
        stats_path  = os.path.join(CAUSAL_DIR, f"layer_{layer_idx}_causal_stats.npy")
        if os.path.exists(causal_path) and os.path.exists(stats_path):
            print(f"Layer {layer_idx:2d}: already verified — skipping")
            continue

        print(f"── Layer {layer_idx:2d} ──")

        sae               = load_sae(layer_idx)
        acts              = load_activations(layer_idx)
        candidate_indices = np.load(
            os.path.join(SCORE_DIR, f"layer_{layer_idx}_topk.npy")
        )
        print(f"  Candidates: {len(candidate_indices)}")

        # Train probe on reconstructed activations for this layer
        print("  Training probe...")
        with torch.no_grad():
            # Use SAE reconstructions as probe input — consistent with ablation
            recons = []
            for start in range(0, len(acts), 512):
                batch = acts[start:start+512].to(DEVICE)
                feat  = sae.encode_only(batch)
                recon = feat @ sae.W_dec.data + sae.b_dec.data
                recons.append(recon.cpu())
            recons_np = torch.cat(recons, dim=0).numpy()

        probe = train_probe(recons_np, train_labels)

        # Run ablation
        print(f"  Ablating {len(candidate_indices)} features...")
        stats        = compute_ablation_stats(sae, probe, acts, candidate_indices)
        causal_mask  = stats[:, 0] >= FLIP_THRESHOLD
        causal_indices = candidate_indices[causal_mask]

        n_causal = causal_mask.sum()
        n_dropped = (~causal_mask).sum()
        print(f"  Causal:      {n_causal} / {len(candidate_indices)}")
        print(f"  Dropped:     {n_dropped} (correlational only)")

        if n_causal > 0:
            top5 = np.argsort(stats[causal_mask, 0])[::-1][:5]
            print(f"  Top 5 causal features by flip rate:")
            causal_stats = stats[causal_mask]
            for rank, idx in enumerate(top5):
                print(f"    #{rank+1}: feature {causal_indices[idx]:>5}  "
                      f"flip={causal_stats[idx,0]:.3f}  "
                      f"delta={causal_stats[idx,1]:.4f}")

        # Save to Drive
        np.save(causal_path, causal_indices)
        np.save(stats_path,  stats)
        plot_causal(stats, candidate_indices, causal_mask, layer_idx)
        print(f"  Saved → {CAUSAL_DIR}/\n")

        summary.append((layer_idx, n_causal, len(candidate_indices)))

        # Free memory
        del sae, acts, probe
        torch.cuda.empty_cache()

    # ── Summary ──
    print(f"\n── Step 4 Complete ──")
    print(f"{'Layer':>6}  {'Causal':>8}  {'Candidates':>11}  {'Kept%':>7}")
    print(f"{'─'*40}")
    for layer_idx, n_causal, n_cand in summary:
        pct = 100 * n_causal / n_cand if n_cand > 0 else 0
        print(f"  {layer_idx:>4}  {n_causal:>8}  {n_cand:>11}  {pct:>6.1f}%")

    total_causal = sum(r[1] for r in summary)
    print(f"\nTotal causal features across all layers: {total_causal}")
    print(f"Saved → {CAUSAL_DIR}/")
    print("Next: Step 5 — map causal features → model weights.")

"""
Step 5 — Map Causal Features to Model Weights (All 32 Layers)
--------------------------------------------------------------
Computes an importance score for every MLP neuron and attention head
in every layer, based on alignment with causal SAE features from Step 4.

Method: cosine similarity between SAE decoder directions and weight directions.
  MLP neuron n output direction:  down_proj.weight[:, n]  shape [4096]
  SAE feature f direction:        W_dec[f]                shape [4096]
  importance(n) = Σ_f |cos_sim(down_proj[:,n], W_dec[f])|

Same for attention heads — project feature direction onto each
head's output subspace via o_proj.

No inference needed — weight matrix operations only.
Mistral loaded on CPU once, all layers processed from it.

Mistral 7B dimensions:
  hidden_size       = 4096
  intermediate_size = 14336
  n_heads           = 32
  n_kv_heads        = 8   (GQA)
  head_dim          = 128

Inputs:
  {DRIVE_ROOT}/sae_models/sae_layer_{N}.pt
  {DRIVE_ROOT}/causal_features/layer_{N}_causal.npy

Output:
  {DRIVE_ROOT}/importance_scores/layer_{N}_mlp_importance.npy   [14336]
  {DRIVE_ROOT}/importance_scores/layer_{N}_head_importance.npy  [32]
"""

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from transformers import AutoModelForCausalLM

# ── Reproducibility ───────────────────────────────────────────────────────────

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# ── Config ────────────────────────────────────────────────────────────────────

TARGET_LAYERS = list(range(32))
MODEL_NAME    = "mistralai/Mistral-7B-v0.1"
N_HEADS       = 32
HEAD_DIM      = 128

# ── Google Drive paths ────────────────────────────────────────────────────────

DRIVE_ROOT  = "/content/drive/MyDrive/sae_pruning"
SAE_DIR     = f"{DRIVE_ROOT}/sae_models"
CAUSAL_DIR  = f"{DRIVE_ROOT}/causal_features"
IMP_DIR     = f"{DRIVE_ROOT}/importance_scores"
os.makedirs(IMP_DIR, exist_ok=True)

# ── SAE decoder loader ────────────────────────────────────────────────────────

class SparseAutoencoder(nn.Module):
    def __init__(self, input_dim, dict_size):
        super().__init__()
        self.input_dim = input_dim
        self.dict_size = dict_size
        self.b_dec = nn.Parameter(torch.zeros(input_dim))
        self.W_enc = nn.Parameter(torch.empty(input_dim, dict_size))
        self.b_enc = nn.Parameter(torch.zeros(dict_size))
        self.W_dec = nn.Parameter(torch.empty(dict_size, input_dim))


def load_sae_decoder(layer_idx):
    """Load W_dec only — all we need for alignment computation."""
    path       = os.path.join(SAE_DIR, f"sae_layer_{layer_idx}.pt")
    checkpoint = torch.load(path, map_location="cpu")
    sae        = SparseAutoencoder(checkpoint["input_dim"], checkpoint["dict_size"])
    sae.load_state_dict(checkpoint["state_dict"])
    return sae.W_dec.data   # [dict_size, 4096]


# ── Importance Computation ────────────────────────────────────────────────────

def compute_mlp_importance(layer, W_dec_causal):
    """
    Each MLP neuron n's output direction = down_proj.weight[:, n]  [4096]
    importance(n) = Σ_f |cos_sim(neuron_n, feature_f)|
    Normalised to [0, 1].

    down_proj.weight shape: [hidden_dim, intermediate_dim] = [4096, 14336]
    columns = neuron output directions
    """
    down_proj    = layer.mlp.down_proj.weight.data          # [4096, 14336]
    neuron_dirs  = F.normalize(down_proj.T.float(), dim=1)  # [14336, 4096]
    feature_dirs = F.normalize(W_dec_causal.float(), dim=1) # [n_causal, 4096]

    cos_sim    = neuron_dirs @ feature_dirs.T               # [14336, n_causal]
    importance = cos_sim.abs().sum(dim=1)                   # [14336]
    importance = importance / (importance.max() + 1e-8)     # normalise [0,1]

    return importance.numpy()


def compute_head_importance(layer, W_dec_causal):
    """
    Head H's output subspace = o_proj.weight[:, H*128:(H+1)*128]  [4096, 128]
    alignment(H, f) = ||W_O_H.T @ W_dec[f]|| (how much head H can express feature f)
    importance(H)   = mean alignment across all causal features
    Normalised to [0, 1].

    o_proj.weight shape: [hidden_dim, n_heads * head_dim] = [4096, 4096]
    """
    o_proj       = layer.self_attn.o_proj.weight.data       # [4096, 4096]
    feature_dirs = F.normalize(W_dec_causal.float(), dim=1) # [n_causal, 4096]
    importance   = torch.zeros(N_HEADS)

    for h in range(N_HEADS):
        W_O_H      = o_proj[:, h * HEAD_DIM : (h + 1) * HEAD_DIM]  # [4096, 128]
        projection = feature_dirs @ W_O_H                           # [n_causal, 128]
        importance[h] = projection.norm(dim=1).mean()

    importance = importance / (importance.max() + 1e-8)
    return importance.numpy()


# ── Plot ──────────────────────────────────────────────────────────────────────

def plot_importance(mlp_imp, head_imp, layer_idx):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].hist(mlp_imp, bins=100, color='steelblue', alpha=0.7)
    axes[0].set_xlabel("Importance Score")
    axes[0].set_ylabel("Number of Neurons")
    axes[0].set_title(f"Layer {layer_idx} — MLP Neuron Importance")
    axes[0].grid(True, alpha=0.3)

    colors = ['steelblue'] * N_HEADS
    axes[1].bar(range(N_HEADS), head_imp, color=colors, alpha=0.8)
    axes[1].set_xlabel("Head Index")
    axes[1].set_ylabel("Importance Score")
    axes[1].set_title(f"Layer {layer_idx} — Attention Head Importance")
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    path = os.path.join(IMP_DIR, f"layer_{layer_idx}_importance.png")
    plt.savefig(path, dpi=150)
    plt.close()


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # Check Drive
    if not os.path.exists(DRIVE_ROOT):
        print("ERROR: Google Drive not mounted.")
        print("Run: from google.colab import drive; drive.mount('/content/drive')")
        exit(1)

    # Only process layers that have both SAE and causal features
    available = [
        l for l in TARGET_LAYERS
        if os.path.exists(os.path.join(SAE_DIR,    f"sae_layer_{l}.pt")) and
           os.path.exists(os.path.join(CAUSAL_DIR, f"layer_{l}_causal.npy"))
    ]
    print(f"Layers ready for importance scoring: {len(available)}")
    print(f"Layers: {available}\n")

    # Load Mistral weights once — used for all layers
    print("Loading Mistral weights (CPU, no inference)...")
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.float32,
        device_map="cpu"
    )
    model.eval()
    print("Weights loaded.\n")

    summary = []

    for layer_idx in available:

        # Skip if already done
        mlp_path  = os.path.join(IMP_DIR, f"layer_{layer_idx}_mlp_importance.npy")
        head_path = os.path.join(IMP_DIR, f"layer_{layer_idx}_head_importance.npy")
        if os.path.exists(mlp_path) and os.path.exists(head_path):
            print(f"Layer {layer_idx:2d}: already scored — skipping")
            continue

        print(f"── Layer {layer_idx:2d} ──")

        # Load causal features
        causal_indices = np.load(
            os.path.join(CAUSAL_DIR, f"layer_{layer_idx}_causal.npy")
        )

        if len(causal_indices) == 0:
            print(f"  No causal features — skipping")
            continue

        W_dec        = load_sae_decoder(layer_idx)          # [dict_size, 4096]
        W_dec_causal = torch.tensor(W_dec[causal_indices])  # [n_causal, 4096]
        print(f"  Causal features: {len(causal_indices)}")

        layer = model.model.layers[layer_idx]

        print("  MLP importance...")
        mlp_imp  = compute_mlp_importance(layer, W_dec_causal)

        print("  Head importance...")
        head_imp = compute_head_importance(layer, W_dec_causal)

        # Save directly to Drive
        np.save(mlp_path,  mlp_imp)
        np.save(head_path, head_imp)
        plot_importance(mlp_imp, head_imp, layer_idx)

        print(f"  MLP  — min={mlp_imp.min():.4f}  "
              f"max={mlp_imp.max():.4f}  "
              f"mean={mlp_imp.mean():.4f}  "
              f"median={np.median(mlp_imp):.4f}")
        print(f"  Head — min={head_imp.min():.4f}  "
              f"max={head_imp.max():.4f}  "
              f"mean={head_imp.mean():.4f}")
        print(f"  Saved → {IMP_DIR}/\n")

        summary.append((layer_idx, len(causal_indices),
                        mlp_imp.mean(), head_imp.mean()))

    # ── Summary ──
    print(f"\n── Step 5 Complete ──")
    print(f"{'Layer':>6}  {'Causal':>8}  {'MLP mean':>10}  {'Head mean':>10}")
    print(f"{'─'*40}")
    for layer_idx, n_causal, mlp_mean, head_mean in summary:
        print(f"  {layer_idx:>4}  {n_causal:>8}  {mlp_mean:>10.4f}  {head_mean:>10.4f}")

    print(f"\nImportance scores saved → {IMP_DIR}/")
    print("Next: Step 6 — apply pruning using these scores.")

"""[9, 17, 13, 31, 23, 22, 29]"""

"""
Step 6 — SAE-Based Structured Pruning
--------------------------------------
Prunes ONLY layers that have SAE importance scores from Step 5.
Layers without scores are left completely untouched.

This keeps pruning principled — every decision is backed by
causal SAE feature analysis. No blind magnitude-based fallback.

As more SAEs are trained (Steps 2-5), re-run this script —
more layers get pruned automatically.

Three-bucket approach per component:
  importance > keep_thresh  → keep as-is       (top 15%)
  prune_thresh < imp < keep → scale down       (middle 15%)
  importance < prune_thresh → zero out         (bottom 70%)

Structured pruning targets:
  MLP neuron n:     gate_proj[n,:], up_proj[n,:], down_proj[:,n]
  Attention head H: q_proj[H*d:(H+1)*d], o_proj[:,H*d:(H+1)*d]
  KV heads:         only if ALL query heads in GQA group are pruned

Inputs:
  {DRIVE_ROOT}/importance_scores/layer_{N}_mlp_importance.npy
  {DRIVE_ROOT}/importance_scores/layer_{N}_head_importance.npy

Output:
  {DRIVE_ROOT}/pruned_model/   HuggingFace model
  {DRIVE_ROOT}/pruned_model/pruning_summary.txt
"""

import os
import torch
import numpy as np
from transformers import AutoModelForCausalLM, AutoTokenizer

# ── Reproducibility ───────────────────────────────────────────────────────────

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# ── Config ────────────────────────────────────────────────────────────────────

MODEL_NAME = "mistralai/Mistral-7B-v0.1"

# Percentile thresholds — applied to each layer's own score distribution
PRUNE_PERCENTILE = 70   # bottom 70% → zero out
SCALE_PERCENTILE = 85   # 70–85%     → scale down
                        # top 15%    → keep as-is

# Mistral 7B GQA
N_HEADS         = 32
N_KV_HEADS      = 8
HEAD_DIM        = 128
HEADS_PER_GROUP = N_HEADS // N_KV_HEADS   # 4 query heads per KV head

# ── Google Drive paths ────────────────────────────────────────────────────────

DRIVE_ROOT = "/content/drive/MyDrive/sae_pruning"
IMP_DIR    = f"{DRIVE_ROOT}/importance_scores"
OUTPUT_DIR = f"{DRIVE_ROOT}/pruned_model"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Utilities ─────────────────────────────────────────────────────────────────

def get_thresholds(importance):
    return (
        float(np.percentile(importance, PRUNE_PERCENTILE)),
        float(np.percentile(importance, SCALE_PERCENTILE))
    )


def bucket_scale(score, prune_thresh, keep_thresh):
    if score >= keep_thresh:
        return 1.0
    elif score <= prune_thresh:
        return 0.0
    else:
        return (score - prune_thresh) / (keep_thresh - prune_thresh + 1e-8)


# ── Pruning ───────────────────────────────────────────────────────────────────

def prune_mlp(layer, importance):
    prune_thresh, keep_thresh = get_thresholds(importance)
    n_pruned = n_scaled = 0

    with torch.no_grad():
        for i, score in enumerate(importance):
            scale = bucket_scale(float(score), prune_thresh, keep_thresh)
            if scale == 1.0:
                continue
            n_pruned += scale == 0.0
            n_scaled += 0.0 < scale < 1.0
            layer.mlp.gate_proj.weight.data[i, :].mul_(scale)
            layer.mlp.up_proj.weight.data[i, :].mul_(scale)
            layer.mlp.down_proj.weight.data[:, i].mul_(scale)

    return int(n_pruned), int(n_scaled)


def prune_attention(layer, importance):
    prune_thresh, keep_thresh = get_thresholds(importance)
    n_pruned = n_scaled = 0

    with torch.no_grad():
        for h in range(N_HEADS):
            scale = bucket_scale(float(importance[h]), prune_thresh, keep_thresh)
            if scale == 1.0:
                continue
            n_pruned += scale == 0.0
            n_scaled += 0.0 < scale < 1.0
            s, e = h * HEAD_DIM, (h + 1) * HEAD_DIM
            layer.self_attn.q_proj.weight.data[s:e, :].mul_(scale)
            layer.self_attn.o_proj.weight.data[:, s:e].mul_(scale)

        # Zero KV head only if ALL query heads in its GQA group are pruned
        for kv_h in range(N_KV_HEADS):
            g_start = kv_h * HEADS_PER_GROUP
            g_end   = g_start + HEADS_PER_GROUP
            if all(importance[h] <= prune_thresh for h in range(g_start, g_end)):
                ks, ke = kv_h * HEAD_DIM, (kv_h + 1) * HEAD_DIM
                layer.self_attn.k_proj.weight.data[ks:ke, :].zero_()
                layer.self_attn.v_proj.weight.data[ks:ke, :].zero_()

    return int(n_pruned), int(n_scaled)


def count_nonzero(model):
    total   = sum(p.numel() for p in model.parameters())
    nonzero = sum(p.data.ne(0).sum().item() for p in model.parameters())
    return total, nonzero


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # Check Drive
    if not os.path.exists(DRIVE_ROOT):
        print("ERROR: Google Drive not mounted.")
        print("Run: from google.colab import drive; drive.mount('/content/drive')")
        exit(1)

    # Find layers with SAE importance scores
    sae_layers = sorted([
        int(f.replace("layer_", "").replace("_mlp_importance.npy", ""))
        for f in os.listdir(IMP_DIR)
        if f.endswith("_mlp_importance.npy")
    ])
    skipped = [l for l in range(32) if l not in sae_layers]

    print(f"Layers with SAE scores : {len(sae_layers)} → {sae_layers}")
    print(f"Layers skipped (no SAE): {len(skipped)}  → {skipped}")
    print(f"Threshold: bottom {PRUNE_PERCENTILE}% pruned | "
          f"{PRUNE_PERCENTILE}-{SCALE_PERCENTILE}% scaled | "
          f"top {100-SCALE_PERCENTILE}% kept\n")

    # Load model
    print("Loading Mistral 7B...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.float16,
        device_map="cpu"
    )
    model.eval()

    total, nonzero_before = count_nonzero(model)
    print(f"Parameters: {total:,}  Non-zero before: {nonzero_before:,}\n")

    summary_rows = []

    for layer_idx in range(32):
        if layer_idx not in sae_layers:
            print(f"  Layer {layer_idx:2d} [---] skipped — no SAE scores")
            summary_rows.append((layer_idx, "---", 0, 0, 0, 0))
            continue

        layer    = model.model.layers[layer_idx]
        mlp_imp  = np.load(os.path.join(IMP_DIR, f"layer_{layer_idx}_mlp_importance.npy"))
        head_imp = np.load(os.path.join(IMP_DIR, f"layer_{layer_idx}_head_importance.npy"))

        mp, ms = prune_mlp(layer, mlp_imp)
        hp, hs = prune_attention(layer, head_imp)

        print(f"  Layer {layer_idx:2d} [SAE] | "
              f"MLP {mp:>5} pruned {ms:>5} scaled | "
              f"Heads {hp:>2} pruned {hs:>2} scaled")

        summary_rows.append((layer_idx, "SAE", mp, ms, hp, hs))

    # ── Stats ──
    _, nonzero_after = count_nonzero(model)
    zeroed     = nonzero_before - nonzero_after
    pct_zeroed = 100 * zeroed / total

    summary = f"""
Pruning Summary
═══════════════════════════════════════════════════════════════════
Model:      {MODEL_NAME}
Strategy:   SAE-only (magnitude fallback disabled)
Threshold:  bottom {PRUNE_PERCENTILE}% pruned | {PRUNE_PERCENTILE}-{SCALE_PERCENTILE}% scaled | top {100-SCALE_PERCENTILE}% kept
Layers pruned:  {len(sae_layers)} / 32
Layers skipped: {len(skipped)} / 32  (untouched — no SAE scores yet)

{'Layer':<8} {'Type':<5} {'MLP pruned':>12} {'MLP scaled':>12} {'Heads pruned':>14} {'Heads scaled':>13}
{'─'*72}"""

    for layer_idx, strat, mp, ms, hp, hs in summary_rows:
        if strat == "---":
            summary += f"\n{layer_idx:<8} {'---':<5} {'(skipped)':>12}"
        else:
            summary += (f"\n{layer_idx:<8} {strat:<5} "
                        f"{mp:>6}/14336  {ms:>6}/14336  "
                        f"{hp:>6}/32      {hs:>6}/32")

    summary += f"""
{'─'*72}
Parameters total  : {total:>15,}
Non-zero before   : {nonzero_before:>15,}
Non-zero after    : {nonzero_after:>15,}
Zeroed out        : {zeroed:>15,}  ({pct_zeroed:.2f}%)
═══════════════════════════════════════════════════════════════════
NOTE: Skipped layers will be pruned when their SAEs are trained.
Re-run this script after completing Steps 2-5 for remaining layers.
"""
    print(summary)

    with open(os.path.join(OUTPUT_DIR, "pruning_summary.txt"), "w") as f:
        f.write(summary)

    print(f"Saving pruned model → {OUTPUT_DIR}/")
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print("Done ✓")

"""
Step 7a — Evaluate: Original vs Pruned (Log Probability)
---------------------------------------------------------
Evaluates sentiment accuracy using log probabilities — more principled
than raw logits because log probs are normalized over the full vocabulary.

Method:
  log_prob("positive") = log_softmax(logits)[pos_token_id]
  log_prob("negative") = log_softmax(logits)[neg_token_id]
  log_odds = log_prob("positive") - log_prob("negative")

  prediction: positive if log_odds > 0, else negative
  confidence: |log_odds| — how certain the model is

Why log probs over raw logits:
  Raw logit for "positive" = 8.2 means nothing in isolation.
  Log prob accounts for the full vocabulary distribution.
  log_odds is a proper scoring rule — directly interpretable as
  "how many nats more likely is positive vs negative".

Metrics:
  Accuracy   — fraction of correct predictions
  F1         — balanced precision/recall
  AUC-ROC    — based on continuous log_odds score (best metric)
  Mean log_odds for pos examples — should be > 0
  Mean log_odds for neg examples — should be < 0

Inputs:
  Original model: mistralai/Mistral-7B-v0.1
  Pruned model:   {DRIVE_ROOT}/pruned_model/

Output:
  {DRIVE_ROOT}/pruned_model/eval_logprob.txt
"""

import os
import torch
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from tqdm import tqdm

# ── Reproducibility ───────────────────────────────────────────────────────────

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# ── Config ────────────────────────────────────────────────────────────────────

ORIGINAL_MODEL = "mistralai/Mistral-7B-v0.1"
EVAL_SIZE      = 200     # 100 pos + 100 neg — balanced
BATCH_SIZE     = 8
MAX_LENGTH     = 512

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ── Google Drive paths ────────────────────────────────────────────────────────

DRIVE_ROOT   = "/content/drive/MyDrive/sae_pruning"
PRUNED_MODEL = f"{DRIVE_ROOT}/pruned_model"

# ── Dataset ───────────────────────────────────────────────────────────────────

def load_eval_data():
    """Balanced: 100 positive + 100 negative from IMDB test."""
    dataset = load_dataset("imdb")
    pos = [x for x in dataset["test"] if x["label"] == 1][:EVAL_SIZE//2]
    neg = [x for x in dataset["test"] if x["label"] == 0][:EVAL_SIZE//2]
    examples = pos + neg
    np.random.shuffle(examples)
    return (
        [x["text"]  for x in examples],
        np.array([x["label"] for x in examples])
    )


def make_prompt(text):
    """Zero-shot sentiment prompt. Truncate to keep prompt short."""
    return f"Review: {text[:400].strip()}\nSentiment (positive/negative):"


# ── Log Probability Evaluation ────────────────────────────────────────────────

def get_sentiment_token_ids(tokenizer):
    """
    Get token IDs for ' positive' and ' negative' (leading space matters).
    Mistral tokenizes ' positive' as a single token.
    Verify this — if either encodes to multiple tokens, the method needs adjustment.
    """
    pos_tokens = tokenizer.encode(" positive", add_special_tokens=False)
    neg_tokens = tokenizer.encode(" negative", add_special_tokens=False)

    assert len(pos_tokens) == 1, \
        f"' positive' encodes to {len(pos_tokens)} tokens — adjust prompt or token choice"
    assert len(neg_tokens) == 1, \
        f"' negative' encodes to {len(neg_tokens)} tokens — adjust prompt or token choice"

    pos_id, neg_id = pos_tokens[0], neg_tokens[0]
    print(f"  Token IDs — ' positive': {pos_id}  ' negative': {neg_id}")
    return pos_id, neg_id


@torch.no_grad()
def predict_batch(model, tokenizer, prompts, pos_id, neg_id):
    """
    For each prompt, compute:
      log_prob_pos = log_softmax(logits[-1])[pos_id]
      log_prob_neg = log_softmax(logits[-1])[neg_id]
      log_odds     = log_prob_pos - log_prob_neg

    Returns:
      preds:     [batch] int  (1=positive, 0=negative)
      log_odds:  [batch] float (positive = model favours positive sentiment)
    """
    encoded = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=MAX_LENGTH
    ).to(DEVICE)

    outputs     = model(**encoded)
    last_logits = outputs.logits[:, -1, :]              # [batch, vocab_size]

    # Convert to log probabilities — normalised over full vocabulary
    log_probs   = torch.log_softmax(last_logits, dim=-1) # [batch, vocab_size]

    log_prob_pos = log_probs[:, pos_id].cpu().numpy()    # [batch]
    log_prob_neg = log_probs[:, neg_id].cpu().numpy()    # [batch]
    log_odds     = log_prob_pos - log_prob_neg           # [batch]

    preds = (log_odds > 0).astype(int)
    return preds, log_odds


# ── Evaluate One Model ────────────────────────────────────────────────────────

def evaluate_model(model_path, tokenizer_path, texts, labels, label):
    print(f"\n{'─'*55}")
    print(f"Evaluating: {label}")
    print(f"{'─'*55}")

    tokenizer = AutoTokenizer.from_pretrained(tokenizer_path)
    tokenizer.pad_token    = tokenizer.eos_token
    tokenizer.padding_side = "left"

    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        torch_dtype=torch.float16,
        device_map="auto"
    )
    model.eval()

    pos_id, neg_id = get_sentiment_token_ids(tokenizer)

    all_preds    = []
    all_log_odds = []
    prompts      = [make_prompt(t) for t in texts]

    for start in tqdm(range(0, len(prompts), BATCH_SIZE), desc="  Predicting"):
        batch = prompts[start : start + BATCH_SIZE]
        preds, log_odds = predict_batch(model, tokenizer, batch, pos_id, neg_id)
        all_preds.extend(preds)
        all_log_odds.extend(log_odds)

    all_preds    = np.array(all_preds)
    all_log_odds = np.array(all_log_odds)

    # ── Metrics ──
    acc = accuracy_score(labels, all_preds)
    f1  = f1_score(labels, all_preds, zero_division=0)
    auc = roc_auc_score(labels, all_log_odds)  # continuous log_odds as score

    # Per-class accuracy
    pos_acc = accuracy_score(labels[labels==1], all_preds[labels==1])
    neg_acc = accuracy_score(labels[labels==0], all_preds[labels==0])

    # Log odds distribution — tells you if model is well-calibrated
    mean_log_odds_pos = all_log_odds[labels==1].mean()
    mean_log_odds_neg = all_log_odds[labels==0].mean()

    print(f"\n  Accuracy    : {acc:.3f}")
    print(f"  F1          : {f1:.3f}")
    print(f"  AUC-ROC     : {auc:.3f}  (based on log_odds — best metric)")
    print(f"  Pos accuracy: {pos_acc:.3f}")
    print(f"  Neg accuracy: {neg_acc:.3f}")
    print(f"\n  Mean log_odds (positive examples): {mean_log_odds_pos:+.3f}  (should be > 0)")
    print(f"  Mean log_odds (negative examples): {mean_log_odds_neg:+.3f}  (should be < 0)")

    del model
    torch.cuda.empty_cache()

    return acc, f1, auc, pos_acc, neg_acc, mean_log_odds_pos, mean_log_odds_neg


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # Check Drive
    if not os.path.exists(DRIVE_ROOT):
        print("ERROR: Google Drive not mounted.")
        print("Run: from google.colab import drive; drive.mount('/content/drive')")
        exit(1)

    print(f"Loading {EVAL_SIZE} balanced IMDB examples...")
    texts, labels = load_eval_data()
    print(f"  Positive: {labels.sum()}  Negative: {(labels==0).sum()}")

    # Evaluate original
    (orig_acc,  orig_f1,  orig_auc,
     orig_pos,  orig_neg,
     orig_lo_pos, orig_lo_neg) = evaluate_model(
        ORIGINAL_MODEL, ORIGINAL_MODEL,
        texts, labels, f"Original {ORIGINAL_MODEL}"
    )

    # Evaluate pruned
    (pruned_acc,  pruned_f1,  pruned_auc,
     pruned_pos,  pruned_neg,
     pruned_lo_pos, pruned_lo_neg) = evaluate_model(
        PRUNED_MODEL, ORIGINAL_MODEL,
        texts, labels, "Pruned Model (no fine-tuning)"
    )

    # ── Report ────────────────────────────────────────────────────────────────

    d_acc = pruned_acc - orig_acc
    d_f1  = pruned_f1  - orig_f1
    d_auc = pruned_auc - orig_auc

    if abs(d_acc) < 0.03:
        verdict = "✓ Minimal damage (< 3%). Fine-tuning optional."
    elif abs(d_acc) < 0.10:
        verdict = "⚠ Moderate damage (3-10%). Fine-tuning recommended."
    else:
        verdict = "✗ Significant damage (> 10%). Fine-tuning required."

    report = f"""
{'═'*60}
EVALUATION REPORT — Log Probability Method
Original vs Pruned (No Fine-Tuning)
{'═'*60}

{'Metric':<25} {'Original':>10}  {'Pruned':>10}  {'Delta':>8}
{'─'*60}
{'Accuracy':<25} {orig_acc:>10.3f}  {pruned_acc:>10.3f}  {d_acc:>+8.3f}
{'F1':<25} {orig_f1:>10.3f}  {pruned_f1:>10.3f}  {d_f1:>+8.3f}
{'AUC-ROC (log_odds)':<25} {orig_auc:>10.3f}  {pruned_auc:>10.3f}  {d_auc:>+8.3f}
{'Pos accuracy':<25} {orig_pos:>10.3f}  {pruned_pos:>10.3f}  {pruned_pos-orig_pos:>+8.3f}
{'Neg accuracy':<25} {orig_neg:>10.3f}  {pruned_neg:>10.3f}  {pruned_neg-orig_neg:>+8.3f}
{'─'*60}
{'Log-odds (pos examples)':<25} {orig_lo_pos:>+10.3f}  {pruned_lo_pos:>+10.3f}
{'Log-odds (neg examples)':<25} {orig_lo_neg:>+10.3f}  {pruned_lo_neg:>+10.3f}

Verdict: {verdict}
{'═'*60}
"""
    print(report)

    with open(os.path.join(PRUNED_MODEL, "eval_logprob.txt"), "w") as f:
        f.write(report)
    print(f"Report saved → {PRUNED_MODEL}/eval_logprob.txt")

"""## Adjusting Pruning Strategy to Improve Negative Sentiment Accuracy

To address the significant drop in negative sentiment accuracy observed after pruning, and to attempt to recover crucial negative sentiment pathways without reducing the overall pruning percentage below 50% too drastically, I will modify the pruning parameters in `prune_model.py`.

### Proposed Changes:
- **`PRUNE_PERCENTILE`**: Changed from `70` to `65`.
  - This means the bottom 65% of components by importance score will be zeroed out, retaining slightly more components than before.
- **`SCALE_PERCENTILE`**: Changed from `85` to `80`.
  - This means components with importance scores between 65% and 80% will be scaled down, and the top 20% will be kept as-is.

This refined strategy aims to be less aggressive, preserving more potentially critical components, which could help in improving the negative sentiment detection. After applying these changes, we will re-run the pruning process and re-evaluate the model's performance.
"""

import os
import torch
import numpy as np
from transformers import AutoModelForCausalLM, AutoTokenizer

# \u2500\u2500 Reproducibility \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)

# \u2500\u2500 Config \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n
MODEL_NAME = "mistralai/Mistral-7B-v0.1"

# Percentile thresholds \u2500 applied to each layer's own score distribution
PRUNE_PERCENTILE = 65   # bottom 65% \u2192 zero out
SCALE_PERCENTILE = 80   # 65\u201380%     \u2192 scale down
                        # top 20%    \u2192 keep as-is

# Mistral 7B GQA
N_HEADS         = 32
N_KV_HEADS      = 8
HEAD_DIM        = 128
HEADS_PER_GROUP = N_HEADS // N_KV_HEADS   # 4 query heads per KV head

# \u2500\u2500 Google Drive paths \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n
DRIVE_ROOT = "/content/drive/MyDrive/sae_pruning"
IMP_DIR    = f"{DRIVE_ROOT}/importance_scores"
OUTPUT_DIR = f"{DRIVE_ROOT}/pruned_model"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# \u2500\u2500 Utilities \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n
def get_thresholds(importance):
    return (
        float(np.percentile(importance, PRUNE_PERCENTILE)),
        float(np.percentile(importance, SCALE_PERCENTILE))
    )


def bucket_scale(score, prune_thresh, keep_thresh):
    if score >= keep_thresh:
        return 1.0
    elif score <= prune_thresh:
        return 0.0
    else:
        return (score - prune_thresh) / (keep_thresh - prune_thresh + 1e-8)


# \u2500\u2500 Pruning \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n
def prune_mlp(layer, importance):
    prune_thresh, keep_thresh = get_thresholds(importance)
    n_pruned = n_scaled = 0

    with torch.no_grad():
        for i, score in enumerate(importance):
            scale = bucket_scale(float(score), prune_thresh, keep_thresh)
            if scale == 1.0:
                continue
            n_pruned += scale == 0.0
            n_scaled += 0.0 < scale < 1.0
            layer.mlp.gate_proj.weight.data[i, :].mul_(scale)
            layer.mlp.up_proj.weight.data[i, :].mul_(scale)
            layer.mlp.down_proj.weight.data[:, i].mul_(scale)

    return int(n_pruned), int(n_scaled)


def prune_attention(layer, importance):
    prune_thresh, keep_thresh = get_thresholds(importance)
    n_pruned = n_scaled = 0

    with torch.no_grad():
        for h in range(N_HEADS):
            scale = bucket_scale(float(importance[h]), prune_thresh, keep_thresh)
            if scale == 1.0:
                continue
            n_pruned += scale == 0.0
            n_scaled += 0.0 < scale < 1.0
            s, e = h * HEAD_DIM, (h + 1) * HEAD_DIM
            layer.self_attn.q_proj.weight.data[s:e, :].mul_(scale)
            layer.self_attn.o_proj.weight.data[:, s:e].mul_(scale)

        # Zero KV head only if ALL query heads in its GQA group are pruned
        for kv_h in range(N_KV_HEADS):
            g_start = kv_h * HEADS_PER_GROUP
            g_end   = g_start + HEADS_PER_GROUP
            if all(importance[h] <= prune_thresh for h in range(g_start, g_end)):
                ks, ke = kv_h * HEAD_DIM, (kv_h + 1) * HEAD_DIM
                layer.self_attn.k_proj.weight.data[ks:ke, :].zero_()
                layer.self_attn.v_proj.weight.data[ks:ke, :].zero_()

    return int(n_pruned), int(n_scaled)


def count_nonzero(model):
    total   = sum(p.numel() for p in model.parameters())
    nonzero = sum(p.data.ne(0).sum().item() for p in model.parameters())
    return total, nonzero


# \u2500\u2500 Main \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n
if __name__ == "__main__":

    # Check Drive
    if not os.path.exists(DRIVE_ROOT):
        print("ERROR: Google Drive not mounted.")
        print("Run: from google.colab import drive; drive.mount('/content/drive')")
        exit(1)

    # Find layers with SAE importance scores
    sae_layers = sorted([
        int(f.replace("layer_", "").replace("_mlp_importance.npy", ""))
        for f in os.listdir(IMP_DIR)
        if f.endswith("_mlp_importance.npy")
    ])
    skipped = [l for l in range(32) if l not in sae_layers]

    print(f"Layers with SAE scores : {len(sae_layers)} \u2192 {sae_layers}")
    print(f"Layers skipped (no SAE): {len(skipped)}  \u2192 {skipped}")
    print(f"Threshold: bottom {PRUNE_PERCENTILE}% pruned | "
          f"{PRUNE_PERCENTILE}-{SCALE_PERCENTILE}% scaled | "
          f"top {100-SCALE_PERCENTILE}% kept\n")

    # Load model
    print("Loading Mistral 7B...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.float16,
        device_map="cpu"
    )
    model.eval()

    total, nonzero_before = count_nonzero(model)
    print(f"Parameters: {total:,d}  Non-zero before: {nonzero_before:,d}\n")

    summary_rows = []

    for layer_idx in range(32):
        if layer_idx not in sae_layers:
            print(f"  Layer {layer_idx:2d} [---] skipped \u2014 no SAE scores")
            summary_rows.append((layer_idx, "---", 0, 0, 0, 0))
            continue

        layer    = model.model.layers[layer_idx]
        mlp_imp  = np.load(os.path.join(IMP_DIR, f"layer_{layer_idx}_mlp_importance.npy"))
        head_imp = np.load(os.path.join(IMP_DIR, f"layer_{layer_idx}_head_importance.npy"))

        mp, ms = prune_mlp(layer, mlp_imp)
        hp, hs = prune_attention(layer, head_imp)

        print(f"  Layer {layer_idx:2d} [SAE] | "
              f"MLP {mp:>6}/14336  {ms:>6}/14336 | "
              f"Heads {hp:>3}/32      {hs:>3}/32")

        summary_rows.append((layer_idx, "SAE", mp, ms, hp, hs))

    # \u2500\u2500 Stats \u2500\u2500\u2500
    _, nonzero_after = count_nonzero(model)
    zeroed     = nonzero_before - nonzero_after
    pct_zeroed = 100 * zeroed / total

    summary = f"""
Pruning Summary
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550
Model:      {MODEL_NAME}
Strategy:   SAE-only (magnitude fallback disabled)
Threshold:  bottom {PRUNE_PERCENTILE}% pruned | {PRUNE_PERCENTILE}-{SCALE_PERCENTILE}% scaled | top {100-SCALE_PERCENTILE}% kept
Layers pruned:  {len(sae_layers)} / 32
Layers skipped: {len(skipped)} / 32  (untouched \u2014 no SAE scores yet)

{'Layer':<8} {'Type':<5} {'MLP pruned':>12} {'MLP scaled':>12} {'Heads pruned':>14} {'Heads scaled':>13}
{'\u2500'*72}"""

    for layer_idx, strat, mp, ms, hp, hs in summary_rows:
        if strat == "---":
            summary += f"\n{layer_idx:<8} {'---':<5} {'(skipped)':>12}"
        else:
            summary += (f"\n{layer_idx:<8} {strat:<5} "
                        f"{mp:>6}/14336  {ms:>6}/14336  "
                        f"{hp:>6}/32      {hs:>6}/32")

    summary += f"""
{'\u2500'*72}
Parameters total  : {total:>15,d}
Non-zero before   : {nonzero_before:>15,d}
Non-zero after    : {nonzero_after:>15,d}
Zeroed out        : {zeroed:>15,d}  ({pct_zeroed:.2f}%)
\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\nNOTE: Skipped layers will be pruned when their SAEs are trained.
Re-run this script after completing Steps 2-5 for remaining layers.
"""
    print(summary)

    with open(os.path.join(OUTPUT_DIR, "pruning_summary.txt"), "w") as f:
        f.write(summary)

    print(f"Saving pruned model \u2192 {OUTPUT_DIR}/")
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print("Done \u2713")

print(report)

